### ISSUE TITLE
KeyError 'Plugins'

### ISSUE THREAD

**Issue by insipx** [s-ol/themer#14]
When I installed themer and try running the "themer plugins" command, i get this error:

```
Enabled activators:
Traceback (most recent call last):
  File "/usr/bin/themer", line 4, in <module>
    __import__('pkg_resources').run_script('Themer==1.0', 'themer')
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 723, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 1643, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/lib/python3.4/site-packages/Themer-1.0-py3.4.egg/EGG-INFO/scripts/themer", line 218, in <module>
KeyError: 'plugins'
```

**Comment by s-ol** [comment]
You are using an old config file that does not contain a "plugins" setting. Please look at the reference config and copy that over.
