### ISSUE TITLE
KeyError when running themer.

### ISSUE THREAD

**Issue by dfryer1193** [s-ol/themer#15]
When running `themer plugins`, I get a KeyError on line 225 on 'plugins'

```
└─(✓)110$> themer plugins
Enabled parsers:
Traceback (most recent call last):
  File "/usr/bin/themer", line 225, in <module>
    for name in config['plugins'][kind]:
KeyError: 'plugins'
```

A similar issue appears when running `themer generate` (same error, different place):

```
└─(✗)111$> themer generate contrast ~/pictures/Contrast.jpg 
Traceback (most recent call last):
  File "/usr/bin/themer", line 263, in <module>
    load_plugins(config)
  File "/usr/bin/themer", line 188, in load_plugins
    for name in config['plugins'][kind]:
KeyError: 'plugins'
```

**Comment by s-ol** [comment]
Have you had an older version installed before? See #14

**Comment by dfryer1193** [comment]
That fixed it, thank you!
