### ISSUE TITLE
Kmeans fails for PNGs

### ISSUE THREAD

**Issue by s-ol** [s-ol/themer#22]
At least very often?

```
Traceback (most recent call last):
  File "/usr/bin/themer", line 294, in <module>
    generate(color_file, config, template_dir, theme_name)
  File "/usr/bin/themer", line 145, in generate
    colors = parse.read()
  File "/usr/lib/python3.4/site-packages/themer/parsers/__init__.py", line 202, in read
    res = super(WallhavenColorParser, self).read(*args)
  File "/usr/lib/python3.4/site-packages/themer/parsers/__init__.py", line 158, in read
    colors = self.get_dominant_colors()
  File "/usr/lib/python3.4/site-packages/themer/parsers/__init__.py", line 141, in get_dominant_colors
    rgbs = kmeans.kmeans(points, self.k)
  File "/usr/lib/python3.4/site-packages/kmeans/__init__.py", line 103, in kmeans
    tolerance=tolerance, max_iterations=max_iterations)
  File "/usr/lib/python3.4/site-packages/kmeans/__init__.py", line 60, in _kmeans
    (r, g, b), count = center
ValueError: too many values to unpack (expected 3)
```

**Comment by goodmind** [comment]
```
Traceback (most recent call last):
  File "/usr/bin/themer", line 294, in <module>
    generate(color_file, config, template_dir, theme_name)
  File "/usr/bin/themer", line 145, in generate
    colors = parse.read()
  File "/usr/lib/python3.4/site-packages/themer/parsers/__init__.py", line 156, in read
    colors = self.get_dominant_colors()
  File "/usr/lib/python3.4/site-packages/themer/parsers/__init__.py", line 139, in get_dominant_colors
    rgbs = kmeans.kmeans(points, self.k)
  File "/usr/lib/python3.4/site-packages/kmeans/__init__.py", line 103, in kmeans
    tolerance=tolerance, max_iterations=max_iterations)
  File "/usr/lib/python3.4/site-packages/kmeans/__init__.py", line 56, in _kmeans
    centers = random.sample(points, k)
  File "/usr/lib/python3.4/random.py", line 315, in sample
    raise ValueError("Sample larger than population")
ValueError: Sample larger than population
```

**Comment by s-ol** [comment]
You don't seem to have the `kmeans` package installed. Can you retry after a `pip install kmeans`?
