### ISSUE TITLE
"unexpected keyword argument 'make_bright'" when generating from .Xresources

### ISSUE THREAD

**Issue by Kmeakin** [s-ol/themer#56]
When trying to generate a theme from a ~/.Xresources file, i get this error:

```
[karl@karlLaptop i3]$ themer generate i3 $HOME/.Xresources
Traceback (most recent call last):
File "/usr/bin/themer", line 323, in <module>
    generate(color_file, config, template_dir, theme_name, options.bright)
File "/usr/bin/themer", line 169, in generate
    parse = parser(color_source, config, logger, make_bright=bright)
TypeError: __init__() got an unexpected keyword argument 'make_bright'
```

**Comment by s-ol** [comment]
Sorry about that, this definitely came from #45 but I should've tested more. As a quick fix you could downgrade one version and I'll look into how to transport the arguments properly, keyword arguments wont do in this fashion.
