### ISSUE TITLE
Python 2.7 Compatibility

### ISSUE THREAD

**Issue by ttrmw** [s-ol/themer#6]
Hi there, 

Trying to get themer working under Ubuntu. Have installed python-setuptools, python-yaml & python-markupsafe, and am now encountering the following issue when calling `themer generate themename image`: 

```
Traceback (most recent call last):
  File "/usr/local/bin/themer", line 4, in <module>
    __import__('pkg_resources').run_script('Themer==0.5', 'themer')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 534, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1444, in run_script
    script_code = compile(script_text, script_filename,'exec')
  File "/usr/local/lib/python2.7/dist-packages/Themer-0.5-py2.7.egg/EGG-INFO/scripts/themer", line 211
    print(msg,file=sys.stderr)
                  ^
SyntaxError: invalid syntax
```

Any pointers?

Cheers!

**Comment by s-ol** [comment]
Themer is currently only working on python3... For this specific error a `from __future__ import print_function` should do.

Please let me know if that is the only thing that's not python2-compatible or if you can get it working just with `__future__` imports. Also please try out v1.0 I am releasing in a minute.

**Comment by ttrmw** [comment]
Thanks for the swift response. Unfortunately the import wasn't enough: 

```
Traceback (most recent call last):
  File "/usr/local/bin/themer", line 4, in <module>
    __import__('pkg_resources').run_script('Themer==0.5', 'themer')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 534, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/Themer-0.5-py2.7.egg/EGG-INFO/scripts/themer", line 24, in <module>

  File "build/bdist.linux-x86_64/egg/themer/__init__.py", line 6, in <module>
ImportError: No module named request
```

**Comment by s-ol** [comment]
Oh yeah, urllib has changed aswell. I'll try to make it compatible with python2 in the future. I still suggest you try python3 anyway, it's the future :P

**Comment by ttrmw** [comment]
Thanks anyway! I will set up virtualenv - I think many things in the Ubuntu repos still depend on system Python being 2.7.

**Comment by Airblader** [comment]
Just have both installed and run themer explicitly with python3 (`python3 themer`)

@S0lll0s You could make the shebang more specific by using `#!/usr/bin/env python3`.

**Comment by s-ol** [comment]
@Airblader sounds like a good idea until (or if I don't) get around to make this 2-3-compatible.
