### ISSUE TITLE
Am I doing something wrong with the install?

### ISSUE THREAD

**Issue by eshrh** [s-ol/themer#62]
I'm not sure what i'm doing wrong, but i installed `themer` manually by cloning the repo, but when i try to run it, i get 

```
Traceback (most recent call last):
  File "/usr/local/bin/themer", line 4, in <module>
    __import__('pkg_resources').run_script('Themer==1.8.2', 'themer')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1674, in run_script
    exec(script_code, namespace, namespace)
  File "/Library/Python/2.7/site-packages/Themer-1.8.2-py2.7.egg/EGG-INFO/scripts/themer", line 46, in <module>
    
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 171, in copytree
    names = os.listdir(src)
OSError: [Errno 2] No such file or directory: '/usr/share/themer/default'
```

Details:
+ Mac os sierra
+ python3.6.2 and python2.7.10
+ all dependencies of themer installed
+ Got hella red errors when i ran setup.py like `_imaging.c:951:14: warning: implicit conversion loses integer precision: 'long'
      to 'int' [-Wshorten-64-to-32]` or sometimes `_imaging.c:559:25: warning: implicit conversion loses integer precision:
      'long long' to 'int' [-Wshorten-64-to-32]` ( i can't paste everything here because its way too long)
+ the reason i'm installing it manually is that when i installed it with pip3 , the command `themer` wasn't found

I'm not sure what i'm doing wrong, can someone please take a look? The script seems awesome and i can't wait to use it!

**Comment by s-ol** [comment]
1. your `PATH` is probably set up wrong if you don't have `themer` after `pip3 install`ing it.
2. this should not be a critical error and I'll change it asap, but the simple fix is to just apply the default configuration yourself: `cp data/default ~/.config/themer` (from inside the cloned repo)
3. no idea about those `setup.py` errors, but that looks like it doesn't have anything to do with themer itself.
