### ISSUE TITLE
AttributeError: module 're' has no attribute '_pattern_type'

### ISSUE THREAD

**Issue by b12f** [s-ol/themer#67]
Just got this after installing with pip and trying out:

```
Traceback (most recent call last):
  File "/home/ben/.local/bin/themer", line 323, in <module>
    generate(color_file, config, template_dir, theme_name, options.bright)
  File "/home/ben/.local/bin/themer", line 167, in generate
    if (isinstance(parser.check, str) or isinstance(parser.check, re._pattern_type)) and not re.search(parser.check, color_source, re.IGNORECASE):
AttributeError: module 're' has no attribute '_pattern_type'
```

I'm not versed in Python, but `re` appears to have gotten an update that changes the API.

**Comment by Soudini** [comment]
From what I could see in another project, re._patern_type has been replaced by re.Pattern
