### ISSUE TITLE
Install default config using setuptools

### ISSUE THREAD

**Issue by s-ol** [s-ol/themer#8]
```
» LayLowz » [~]: themer generate green_theme wallhaven-68460.png 
/usr/lib/python3/dist-packages/pkg_resources.py:1049: UserWarning: /home/LayLowz/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
Traceback (most recent call last):
  File "/usr/local/bin/themer", line 4, in &lt;module&gt;
    __import__('pkg_resources').run_script('Themer==1.0', 'themer')
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 534, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.4/dist-packages/Themer-1.0-py3.4.egg/EGG-INFO/scripts/themer", line 255, in &lt;module&gt;
  File "/usr/local/lib/python3.4/dist-packages/Themer-1.0-py3.4.egg/EGG-INFO/scripts/themer", line 59, in read_config
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by s-ol** [comment]
Finally got around to doing this in 5afdbaa9f766bdab28c8b7f33415feb69bc1535e
